version: '3.1'

services:
  mongodb:
    image: mongo:4.4.15
    container_name: mongodb
    restart: unless-stopped
    env_file: development.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
    ports:
      - "27017:27017"
    networks:
      - development-network

networks:
  development-network:
    driver: bridge
